# Generated by Django 5.2.10 on 2026-02-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Código del producto (ej. API Tersa)', max_length=100, verbose_name='Código'),
        ),
    ]
