# Generated by Django 5.2.10 on 2026-02-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraddress'),
        ('products', '0006_add_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name='Vistas'
            ),
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Vista de producto',
                'verbose_name_plural': 'Vistas de productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productview',
            constraint=models.UniqueConstraint(
                condition=models.Q(user__isnull=False),
                fields=('product', 'user'),
                name='products_unique_product_user_view',
            ),
        ),
        migrations.AddConstraint(
            model_name='productview',
            constraint=models.UniqueConstraint(
                condition=models.Q(user__isnull=True),
                fields=('product', 'session_key'),
                name='products_unique_product_session_view',
            ),
        ),
    ]
