# Generated by Django 5.2.10 on 2026-02-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraddress'),
        ('products', '0007_product_views_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to='products.product'
                    )
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorite_products',
                        to='accounts.user'
                    )
                ),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productfavorite',
            constraint=models.UniqueConstraint(
                fields=('product', 'user'),
                name='products_unique_product_favorite_user',
            ),
        ),
    ]
