# Generated by Django 5.2.10 on 2026-02-28 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del producto en la API externa (ej. Tersa)', max_length=100, verbose_name='ID API'),
        ),
        migrations.CreateModel(
            name='ProductStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product')),
            ],
            options={
                'verbose_name': 'Alerta de stock',
                'verbose_name_plural': 'Alertas de stock',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'email'), name='products_unique_product_email_stock_alert')],
            },
        ),
    ]
