# Generated by Django 5.2.10 on 2026-02-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_state_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_customer_type',
            field=models.CharField(choices=[('person', 'Persona natural'), ('company', 'Empresa')], default='person', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_document_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de identificación'),
        ),
    ]
