# Generated by Django 5.2.10 on 2026-02-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_billing_customer_type_document_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
