# Generated by Django 5.2.10 on 2026-02-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_billing_last_name_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_document_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
