# Generated by Django 5.2.10 on 2026-02-28 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_document_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('internal', 'Nota interna'), ('client', 'Nota al cliente')], default='internal', max_length=20)),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notes', to='orders.order')),
            ],
            options={
                'verbose_name': 'Nota de pedido',
                'verbose_name_plural': 'Notas de pedido',
                'ordering': ['-created_at'],
            },
        ),
    ]
