# Generated by Django 5.2.10 on 2026-02-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Si está definido, ya se envió el correo de recordatorio para completar el pago.', null=True, verbose_name='Recordatorio de pago enviado'),
        ),
    ]
