# Generated by Django 5.2.10 on 2026-02-28 01:17

from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(status='completed', completed_at__isnull=True):
        order.completed_at = order.updated_at
        order.save(update_fields=['completed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_payment_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el pedido pasó a estado completado (para reseñas y recordatorios).', null=True, verbose_name='Completado/entregado'),
        ),
        migrations.AddField(
            model_name='order',
            name='repurchase_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recordatorio de recompra enviado'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_request_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solicitud de reseña enviada'),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
    ]
