# Generated by Django 5.2.10 on 2026-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_review_repurchase_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('on_hold', 'En espera'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
    ]
