# Generated by Django 5.2.10 on 2026-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento / Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Cliente'), ('wholesale', 'Cliente mayorista'), ('staff', 'Staff'), ('admin', 'Administrador')], default='client', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
