# Generated by Django 5.2.10 on 2026-02-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_state_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('person', 'Persona natural'), ('company', 'Empresa')], default='person', max_length=20, verbose_name='Registrado como'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de identificación'),
        ),
    ]
