# Generated by Django 5.2.10 on 2026-02-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_customer_type_document_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], default='', max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
