# Generated by Django 5.2.10 on 2026-02-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCartLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cart_snapshot', models.JSONField(default=list, help_text='Lista de items: {product_id, product_name, quantity, price, total}', verbose_name='Snapshot del carrito')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total del carrito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead carrito abandonado',
                'verbose_name_plural': 'Leads carrito abandonado',
                'ordering': ['-created_at'],
            },
        ),
    ]
