# Generated by Django 5.2.10 on 2026-02-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='The BARBERSHOP', max_length=200, verbose_name='Nombre de la tienda')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Slogan o descripción breve')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('business_hours', models.CharField(blank=True, help_text='Ej: Lun a Dom 9:00am a 6:00pm', max_length=200, verbose_name='Horario de atención')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('about_text', models.TextField(blank=True, verbose_name='Texto sobre nosotros')),
                ('currency', models.CharField(default='$', max_length=10, verbose_name='Moneda')),
                ('terms_url', models.URLField(blank=True, verbose_name='URL términos y condiciones')),
                ('privacy_url', models.URLField(blank=True, verbose_name='URL política de privacidad')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta descripción (SEO)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
