# Generated by Django 5.2.10 on 2026-02-16 23:27

from django.db import migrations, models


def create_default_sections(apps, schema_editor):
    HomeSection = apps.get_model('core', 'HomeSection')
    defaults = [
        ('hero', 0), ('about', 1), ('brands', 2), ('products', 3),
        ('meat_category', 4), ('pricing', 5), ('delivery', 6),
        ('why_choose', 7), ('testimonials', 8), ('why_choose_three', 9), ('blog', 10),
    ]
    for key, order in defaults:
        HomeSection.objects.get_or_create(section_key=key, defaults={'order': order})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_addsitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo / Tagline')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='home/about/', verbose_name='Imagen principal')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='home/about/', verbose_name='Imagen secundaria')),
                ('experience_years', models.CharField(blank=True, max_length=20, verbose_name='Años de experiencia')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Texto del botón')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='URL del botón')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloque sobre nosotros',
                'verbose_name_plural': 'Bloque sobre nosotros',
            },
        ),
        migrations.CreateModel(
            name='HomeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('logo', models.ImageField(upload_to='home/brands/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título principal')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Subtítulo')),
                ('text', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/hero/', verbose_name='Imagen')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Texto del botón')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='URL del botón')),
                ('video_url', models.URLField(blank=True, verbose_name='URL video (YouTube)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Slide hero',
                'verbose_name_plural': 'Slides hero',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero', 'Hero / Slider'), ('about', 'Sobre nosotros'), ('brands', 'Marcas / Clientes'), ('products', 'Productos destacados'), ('meat_category', 'Categorías'), ('pricing', 'Precios'), ('delivery', 'Entrega'), ('why_choose', 'Por qué elegirnos'), ('testimonials', 'Testimonios'), ('why_choose_three', 'Por qué elegirnos 2'), ('blog', 'Blog / Noticias')], max_length=50, unique=True, verbose_name='Clave')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Sección del home',
                'verbose_name_plural': 'Secciones del home',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Cargo / rol')),
                ('text', models.TextField(verbose_name='Testimonio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/testimonials/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(create_default_sections, migrations.RunPython.noop),
    ]
