# Generated by Django 5.2.10 on 2026-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_country_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento / Estado'),
        ),
    ]
