# Generated by Django 5.2.10 on 2026-02-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_state_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de envío')),
                ('delivery_days', models.PositiveIntegerField(default=3, help_text='Cantidad de días hábiles para la entrega', verbose_name='Días de entrega')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_price', to='core.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Precio de envío por ciudad',
                'verbose_name_plural': 'Precios de envío por ciudad',
                'ordering': ['city__state__name', 'city__name'],
            },
        ),
    ]
