# Generated by Django 5.2.10 on 2026-02-17 18:21

from django.db import migrations, models


def copy_delivery_days_to_range(apps, schema_editor):
    ShippingPrice = apps.get_model('core', 'ShippingPrice')
    for sp in ShippingPrice.objects.all():
        if hasattr(sp, 'delivery_days'):
            sp.delivery_days_min = sp.delivery_days
            sp.delivery_days_max = sp.delivery_days
            sp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='delivery_days_max',
            field=models.PositiveIntegerField(default=3, help_text='Máximo de días hábiles para la entrega', verbose_name='Días de entrega (máximo)'),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='delivery_days_min',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de días hábiles para la entrega', verbose_name='Días de entrega (mínimo)'),
        ),
        migrations.RunPython(copy_delivery_days_to_range, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='shippingprice',
            name='delivery_days',
        ),
    ]
