# Generated by Django 5.2.10 on 2026-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shipping_delivery_days_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeheroslide',
            name='shape_image',
            field=models.ImageField(blank=True, help_text='Forma decorativa sobre la imagen. Si está vacío se usa la imagen por defecto.', null=True, upload_to='home/hero/shapes/', verbose_name='Imagen decorativa (shape)'),
        ),
    ]
