# Generated by Django 5.2.10 on 2026-02-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_hero_slide_shape_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_out_of_stock_products',
            field=models.BooleanField(default=True, help_text='Si está desactivado, los productos sin stock no se mostrarán en la tienda ni en el home.', verbose_name='Mostrar productos sin stock'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ej: https://www.youtube.com/watch?v=xxxxx. Si lo completas, se mostrará el botón de play sobre la imagen del slide.', verbose_name='URL video (YouTube)'),
        ),
    ]
