# Generated by Django 5.2.10 on 2026-02-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_show_out_of_stock_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMeatCategoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, default='primera opción', max_length=150, verbose_name='Subtítulo / Tagline')),
                ('title', models.CharField(blank=True, default='Las mejores categorías en nuestra tienda', max_length=300, verbose_name='Título')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='home/meat_category/', verbose_name='Imagen superior')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home/meat_category/', verbose_name='Imagen de fondo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección categorías (meat-category)',
                'verbose_name_plural': 'Sección categorías (meat-category)',
            },
        ),
    ]
