# Generated by Django 5.2.10 on 2026-02-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_home_meat_category_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='topbar_marquee_text',
            field=models.TextField(blank=True, help_text='Texto que se muestra en la barra superior en movimiento. Si está vacío, la barra no se muestra.', verbose_name='Texto barra superior (marquee)'),
        ),
    ]
