# Generated by Django 5.2.10 on 2026-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_topbar_marquee_default_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='topbar_marquee_text',
            field=models.TextField(blank=True, default='Por compras superiores a $120.000 el envío es gratis', help_text='Texto que se muestra en la barra superior en movimiento. Si está vacío, la barra no se muestra.', verbose_name='Texto barra superior (marquee)'),
        ),
    ]
