# Generated by Django 5.2.10 on 2026-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_tiktok_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBrandBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Imagen de fondo de la sección de marcas. Si está vacío se usa la imagen por defecto.', null=True, upload_to='home/brands/', verbose_name='Imagen de fondo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección marcas (config)',
                'verbose_name_plural': 'Sección marcas (config)',
            },
        ),
    ]
