# Generated by Django 5.2.10 on 2026-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_home_brand_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Si el subtotal del pedido es mayor o igual a este valor, el envío será gratis.', max_digits=12, verbose_name='Envío gratis desde'),
        ),
    ]
