# Generated by Django 5.2.10 on 2026-03-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sitesettings_maintenance_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_body_html',
            field=models.TextField(blank=True, help_text='Código HTML que se inserta al inicio del body. Útil para pixels (Facebook, TikTok, etc.), scripts de tracking y conversiones. Solo visible en el sitio público, no en el panel.', verbose_name='HTML personalizado en el body'),
        ),
    ]
