# Generated by Django 5.2.10 on 2026-03-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_custom_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(blank=True, help_text='URL base del sitio (ej: https://barbershop.com.co). Se usa en emails y enlaces. Si está vacío se usa la URL de la petición cuando está disponible.', verbose_name='URL del sitio'),
        ),
    ]
