# Generated by Django 5.2.10 on 2026-02-18 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_add_state_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wompi_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Wompi')),
                ('reference', models.CharField(db_index=True, help_text='Número de pedido enviado como referencia a Wompi', max_length=100, verbose_name='Referencia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Declinado'), ('VOIDED', 'Anulado'), ('ERROR', 'Error')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('amount_in_cents', models.BigIntegerField(default=0, verbose_name='Monto (centavos)')),
                ('currency', models.CharField(default='COP', max_length=10, verbose_name='Moneda')),
                ('payment_method_type', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Datos crudos Wompi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wompi_transactions', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Transacción Wompi',
                'verbose_name_plural': 'Transacciones Wompi',
                'ordering': ['-created_at'],
            },
        ),
    ]
